=== diegomarty00/sew-23-24/Practica9/Ejercicio2/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/rutas" elementFormDefault="qualified" targetNamespace="http://tempuri.org/rutas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datos" />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="nombreRuta" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="datos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tipoRuta" />
				<xs:element ref="medioTransporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fechaIni" />
				<xs:element minOccurs="0" maxOccurs="1" ref="horaIni" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcionRuta" />
				<xs:element ref="sugerencias" />
				<xs:element ref="lugar" />
				<xs:element ref="direccion" />
				<xs:element ref="coordenadasRuta" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
				<xs:element ref="recomendacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tipoRuta" type="xs:string" />
	<xs:element name="medioTransporte" type="xs:string" />
	<xs:element name="fechaIni" type="xs:string" />
	<xs:element name="horaIni" type="xs:string" />
	<xs:element name="duracion" type="xs:string" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcionRuta" type="xs:string" />
	<xs:element name="sugerencias" type="xs:string" />
	<xs:element name="lugar" type="xs:string" />
	<xs:element name="direccion" type="xs:string" />
	<xs:element name="referencia" type="xs:string" />

	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction  base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="coordenadasRuta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="descripcionHito" />
				<xs:element ref="coordenadasHito" />
				<xs:element ref="distancia" />
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
			<xs:attribute name="nombreHito" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadasHito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="descripcionHito" type="xs:string" />
	<xs:element name="distancia" type="xs:string" />
	<xs:element name="foto" type="xs:string" />
	<xs:element name="video" type="xs:string" />
	<xs:element name="longitud" type="xs:decimal" />
	<xs:element name="latitud" type="xs:decimal" />
	<xs:element name="altitud" type="xs:decimal" />
</xs:schema>

=== diegomarty00/sew-23-24/EscritorioVirtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es rutas.xsd"
>
	<ruta nombreRuta="Amphitheatre Viewpoint – Tugela Gorge Recorrido circular desde Bonjaneni" > 
		<datos>
			<tipoRuta>Senderismo</tipoRuta>
			<medioTransporte>A pie</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.7112194</longitud>
				<latitud>28.9335923</latitud>
				<altitud>18.08</altitud>
			</coordenadasRuta>
			<duracion>4 horas 38 minutos - 12,6 km</duracion>
			<agencia>Ninguna</agencia>
			<descripcionRuta>Caminata moderada. Se necesita buena forma física. 
				Sendas accesibles en su mayoría. Se requiere tener paso firme. 
				El punto de inicio de la Ruta está junto a un aparcamiento.</descripcionRuta>
			<sugerencias>Llevar agua</sugerencias>
			<lugar>Bonjaneni</lugar>
			<direccion>Thendele Camp, Royal Natal Park, Sudáfrica</direccion>
			<referencia>https://www.komoot.com/es-es/smarttour/109968</referencia>
			<referencia>https://es.wikipedia.org/wiki/Salto_del_Tugela</referencia>
			<referencia>https://en.wikipedia.org/wiki/Amphitheatre_(Drakensberg)</referencia>
			<recomendacion>9</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Mushroomrock">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7112194</longitud>
					<latitud>28.9335923</latitud>
					<altitud>18.08</altitud>
				</coordenadasHito>
				<distancia>1960</distancia>
				<foto>Mushroomrock.png</foto>
			</hito>
			<hito nombreHito="Amphitheatre">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7594444</longitud>
					<latitud>28.8741134</latitud>
					<altitud>14</altitud>
				</coordenadasHito>
				<distancia>4000</distancia>
				<foto>Amphitheatre.jpg</foto>
			</hito>
			<hito nombreHito="Tugela Schlucht (George)">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7612577</longitud>
					<latitud>28.8870956</latitud>
					<altitud>13.75</altitud>
				</coordenadasHito>
				<distancia>6030</distancia>
				<foto>TugelaSchlucht.jpg</foto>
				<video>https://www.youtube.com/watch?v=tlZR29yV9K4</video>
			</hito>
		</hitos>
	</ruta>


	<ruta nombreRuta="Rock Pool – Black Pool Recorrido circular desde Ha Lehloara" > 
		<datos>
			<tipoRuta>Senderismo</tipoRuta>
			<medioTransporte>A pie</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.9159641</longitud>
				<latitud>28.4234915</latitud>
				<altitud>14.5</altitud>
			</coordenadasRuta>
			<duracion>2 horas 43 minutos - 9,22 km</duracion>
			<agencia>Ninguna</agencia>
			<descripcionRuta>Caminata difícil. Se necesita muy buena forma física. Sendas de fácil acceso. Para todos los niveles.</descripcionRuta>
			<sugerencias>Llevar agua</sugerencias>
			<lugar>Hotel Maliba Lodge</lugar>
			<direccion>Hotel Maliba Lodge, Lesoto, Sudáfrica</direccion>
			<referencia>https://www.komoot.com/es-es/smarttour/19154415</referencia>
			<referencia>https://www.booking.com/Share-CsatN36</referencia>
			<referencia>https://maliba-lodge.com</referencia>
			<recomendacion>8</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Hotel Maliba Lodge">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9159641</longitud>
					<latitud>28.4234915</latitud>
					<altitud>14.5</altitud>
				</coordenadasHito>
				<distancia>0</distancia>
				<foto>HotelMalibaLodge.jpg</foto>
			</hito>
			<hito nombreHito="Black Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.899246</longitud>
					<latitud>28.453383</latitud>
					<altitud>14.7</altitud>
				</coordenadasHito>
				<distancia>5180</distancia>
				<foto>BlackPool.png</foto>
			</hito>
			<hito nombreHito="Rock Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9163853</longitud>
					<latitud>28.4432391</latitud>
					<altitud>16.5</altitud>
				</coordenadasHito>
				<distancia>12800</distancia>
				<foto>RockPool.png</foto>
			</hito>
		</hitos>
	</ruta>


	<ruta nombreRuta="Black Pool – Rock Pool Recorrido circular desde Ha Lehloara" > 
		<datos>
			<tipoRuta>Senderismo</tipoRuta>
			<medioTransporte>A pie</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.9159641</longitud>
				<latitud>28.4234915</latitud>
				<altitud>14.5</altitud>
			</coordenadasRuta>
			<duracion>5 horas 7 minutos - 14,2 km</duracion>
			<agencia>Ninguna</agencia>
			<descripcionRuta>Caminata difícil. Se necesita muy buena forma física. Sendas de fácil acceso. Para todos los niveles.</descripcionRuta>
			<sugerencias>Llevar agua</sugerencias>
			<lugar>Hotel Maliba Lodge</lugar>
			<direccion>Hotel Maliba Lodge, Lesoto, Sudáfrica</direccion>
			<referencia>https://www.komoot.com/es-es/smarttour/19154415</referencia>
			<referencia>https://www.booking.com/Share-CsatN36</referencia>
			<referencia>https://maliba-lodge.com</referencia>
			<recomendacion>7</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Hotel Maliba Lodge">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9159641</longitud>
					<latitud>28.4234915</latitud>
					<altitud>14.5</altitud>
				</coordenadasHito>
				<distancia>0</distancia>
				<foto>HotelMalibaLodge.jpg</foto>
			</hito>
			<hito nombreHito="Black Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.899246</longitud>
					<latitud>28.453383</latitud>
					<altitud>14.7</altitud>
				</coordenadasHito>
				<distancia>5180</distancia>
				<foto>BlackPool.png</foto>
			</hito>
			<hito nombreHito="Rock Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9163853</longitud>
					<latitud>28.4432391</latitud>
					<altitud>16.5</altitud>
				</coordenadasHito>
				<distancia>12800</distancia>
				<foto>RockPool.png</foto>
			</hito>
		</hitos>
	</ruta>
</rutas>
