=== diegomarty00/sew-23-24/Practica 2/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta  (datos, hitos)>
<!ELEMENT datos (tipoRuta, medioTransporte, 
	fechaIni?, horaIni?, duracion, 
	agencia, descripcionRuta, sugerencias,
	lugar, direccion, coordenadasRuta, referencia+, 
	recomendacion)>
	
<!ELEMENT tipoRuta (#PCDATA)>
<!ELEMENT medioTransporte (#PCDATA)>
<!ELEMENT fechaIni (#PCDATA)>
<!ELEMENT horaIni (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcionRuta (#PCDATA)>
<!ELEMENT sugerencias (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT coordenadasRuta (longitud, latitud, altitud)>
<!ELEMENT hitos (hito*)>

<!ELEMENT hito (descripcionHito, coordenadasHito, 
	distancia, foto+, video* )>
<!ELEMENT coordenadasHito (longitud, latitud, altitud)>
<!ELEMENT descripcionHito (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ATTLIST ruta 
	nombreRuta CDATA #REQUIRED>	
<!ATTLIST hito 
	nombreHito CDATA #REQUIRED>

=== diegomarty00/sew-23-24/Practica 2/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd"> 


<rutas>
	<ruta nombreRuta="Amphitheatre Viewpoint – Tugela Gorge Recorrido circular desde Bonjaneni" > 
		<datos>
			<tipoRuta>"Senderismo"</tipoRuta>
			<medioTransporte>"A pie"</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.7112194</longitud>
				<latitud>28.9335923</latitud>
				<altitud>18.08</altitud>
			</coordenadasRuta>
			<fechaIni></fechaIni>
			<horaIni></horaIni>
			<duracion>"4 horas 38 minutos - 12,6 km"</duracion>
			<agencia>"Ninguna"</agencia>
			<descripcionRuta>"Caminata moderada. Se necesita buena forma física. 
				Sendas accesibles en su mayoría. Se requiere tener paso firme. 
				El punto de inicio de la Ruta está junto a un aparcamiento."</descripcionRuta>
			<sugerencias>"Llevar agua"</sugerencias>
			<lugar>"Bonjaneni"</lugar>
			<direccion>"Thendele Camp, Royal Natal Park, Sudáfrica"</direccion>
			<referencia>"https://www.komoot.com/es-es/smarttour/109968"</referencia>
			<recomendacion>9.8</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Mushroomrock">
				<descripcionHito>"Lugar favorito para senderismo"</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7112194</longitud>
					<latitud>28.9335923</latitud>
					<altitud>18.08</altitud>
				</coordenadasHito>
				<distancia>"1.96km"</distancia>
				<foto>"algo"</foto>
				<video>"algo"</video>
			</hito>
		</hitos>
		
		
	</ruta>
</rutas>

=== diegomarty00/sew-23-24/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd"> 


<rutas>
	<ruta nombreRuta="Amphitheatre Viewpoint – Tugela Gorge Recorrido circular desde Bonjaneni" > 
		<datos>
			<tipoRuta>Senderismo</tipoRuta>
			<medioTransporte>A pie</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.7112194</longitud>
				<latitud>28.9335923</latitud>
				<altitud>18.08</altitud>
			</coordenadasRuta>
			<duracion>4 horas 38 minutos - 12,6 km</duracion>
			<agencia>Ninguna</agencia>
			<descripcionRuta>Caminata moderada. Se necesita buena forma física. 
				Sendas accesibles en su mayoría. Se requiere tener paso firme. 
				El punto de inicio de la Ruta está junto a un aparcamiento.</descripcionRuta>
			<sugerencias>Llevar agua</sugerencias>
			<lugar>Bonjaneni</lugar>
			<direccion>Thendele Camp, Royal Natal Park, Sudáfrica</direccion>
			<referencia>https://www.komoot.com/es-es/smarttour/109968</referencia>
			<referencia>https://es.wikipedia.org/wiki/Salto_del_Tugela</referencia>
			<referencia>https://en.wikipedia.org/wiki/Amphitheatre_(Drakensberg)</referencia>
			<recomendacion>9.8</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Mushroomrock">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7112194</longitud>
					<latitud>28.9335923</latitud>
					<altitud>18.08</altitud>
				</coordenadasHito>
				<distancia>1.96km</distancia>
				<foto>https://d2exd72xrrp1s7.cloudfront.net/www/000/1k5/19/19cwo80rifpj81s7jyp2lof0cq3qrrwn90-uhi31781453/0</foto>
			</hito>
			<hito nombreHito="Amphitheatre">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7594444</longitud>
					<latitud>28.8741134</latitud>
					<altitud>14</altitud>
				</coordenadasHito>
				<distancia>4.00km</distancia>
				<foto>https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Amphitheatre_Drakensberg.jpg/1280px-Amphitheatre_Drakensberg.jpg</foto>
			</hito>
			<hito nombreHito="Tugela Schlucht (George)">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.7612577</longitud>
					<latitud>28.8870956</latitud>
					<altitud>13.75</altitud>
				</coordenadasHito>
				<distancia>6.03km</distancia>
				<foto>https://dynamic-media-cdn.tripadvisor.com/media/photo-o/24/c0/3c/74/caption.jpg</foto>
				<video>https://www.youtube.com/watch?v=tlZR29yV9K4</video>
			</hito>
		</hitos>
	</ruta>


	<ruta nombreRuta="Rock Pool – Black Pool Recorrido circular desde Ha Lehloara" > 
		<datos>
			<tipoRuta>Senderismo</tipoRuta>
			<medioTransporte>A pie</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.9159641</longitud>
				<latitud>28.4234915</latitud>
				<altitud>14.5</altitud>
			</coordenadasRuta>
			<duracion>2 horas 43 minutos - 9,22 km</duracion>
			<agencia>Ninguna</agencia>
			<descripcionRuta>Caminata difícil. Se necesita muy buena forma física. Sendas de fácil acceso. Para todos los niveles.</descripcionRuta>
			<sugerencias>Llevar agua</sugerencias>
			<lugar>Hotel Maliba Lodge</lugar>
			<direccion>Hotel Maliba Lodge, Lesoto, Sudáfrica</direccion>
			<referencia>https://www.komoot.com/es-es/smarttour/19154415</referencia>
			<referencia>https://www.booking.com/Share-CsatN36</referencia>
			<referencia>https://maliba-lodge.com</referencia>
			<recomendacion>8.3</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Hotel Maliba Lodge">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9159641</longitud>
					<latitud>28.4234915</latitud>
					<altitud>14.5</altitud>
				</coordenadasHito>
				<distancia>0km</distancia>
				<foto>https://cf.bstatic.com/xdata/images/hotel/max1024x768/377515576.jpg</foto>
			</hito>
			<hito nombreHito="Black Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.899246</longitud>
					<latitud>28.453383</latitud>
					<altitud>14.7</altitud>
				</coordenadasHito>
				<distancia>5.18km</distancia>
				<foto>https://d2exd72xrrp1s7.cloudfront.net/www/000/1k7/10/100l6e4rfsj6n1glq0hkic44ve4nrmbl5y-uhi63111461/0</foto>
			</hito>
			<hito nombreHito="Rock Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9163853</longitud>
					<latitud>28.4432391</latitud>
					<altitud>16.5</altitud>
				</coordenadasHito>
				<distancia>12.8km</distancia>
				<foto>https://d2exd72xrrp1s7.cloudfront.net/www/000/1k7/5y/5ysohw5fyc2tmtz2mmmc0zzg4nrmh0ry-uhi63111648/0</foto>
			</hito>
		</hitos>
	</ruta>


	<ruta nombreRuta="Black Pool – Rock Pool Recorrido circular desde Ha Lehloara" > 
		<datos>
			<tipoRuta>Senderismo</tipoRuta>
			<medioTransporte>A pie</medioTransporte>
			<coordenadasRuta>
				<longitud>-28.9159641</longitud>
				<latitud>28.4234915</latitud>
				<altitud>14.5</altitud>
			</coordenadasRuta>
			<duracion>5 horas 7 minutos - 14,2 km</duracion>
			<agencia>Ninguna</agencia>
			<descripcionRuta>Caminata difícil. Se necesita muy buena forma física. Sendas de fácil acceso. Para todos los niveles.</descripcionRuta>
			<sugerencias>Llevar agua</sugerencias>
			<lugar>Hotel Maliba Lodge</lugar>
			<direccion>Hotel Maliba Lodge, Lesoto, Sudáfrica</direccion>
			<referencia>https://www.komoot.com/es-es/smarttour/19154415</referencia>
			<referencia>https://www.booking.com/Share-CsatN36</referencia>
			<referencia>https://maliba-lodge.com</referencia>
			<recomendacion>7.6</recomendacion>
		</datos>
		<hitos>
			<hito nombreHito="Hotel Maliba Lodge">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9159641</longitud>
					<latitud>28.4234915</latitud>
					<altitud>14.5</altitud>
				</coordenadasHito>
				<distancia>0km</distancia>
				<foto>https://cf.bstatic.com/xdata/images/hotel/max1024x768/377515576.jpg</foto>
			</hito>
			<hito nombreHito="Black Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.899246</longitud>
					<latitud>28.453383</latitud>
					<altitud>14.7</altitud>
				</coordenadasHito>
				<distancia>5.18km</distancia>
				<foto>https://d2exd72xrrp1s7.cloudfront.net/www/000/1k7/10/100l6e4rfsj6n1glq0hkic44ve4nrmbl5y-uhi63111461/0</foto>
			</hito>
			<hito nombreHito="Rock Pool">
				<descripcionHito>Lugar favorito para senderismo</descripcionHito>
				<coordenadasHito>
					<longitud>-28.9163853</longitud>
					<latitud>28.4432391</latitud>
					<altitud>16.5</altitud>
				</coordenadasHito>
				<distancia>12.8km</distancia>
				<foto>https://d2exd72xrrp1s7.cloudfront.net/www/000/1k7/5y/5ysohw5fyc2tmtz2mmmc0zzg4nrmh0ry-uhi63111648/0</foto>
			</hito>
		</hitos>
	</ruta>
</rutas>
